apiVersion: v1
kind: Service
metadata:
  name: ha-website-service
spec:
  type: NodePort
  selector:
    app: ha-website
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    # NodePort will be automatically assigned in range 30000-32767
    # You can specify a fixed port if needed, e.g., nodePort: 30080
  sessionAffinity: ClientIP
